spring:
  datasource:
    url: jdbc:sqlserver://qavmsdbserver.database.windows.net:1433;database=qavmsdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: avdevops
    password: d3v0p$@dm1n
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191

